FROM openjdk:8-jre-slim
MAINTAINER xuxueli

ENV PARAMS=""

ENV TZ=PRC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ADD target/xxl-job-admin-*.jar /app/app.jar

ENTRYPOINT ["sh","-c","java -jar $JAVA_OPTS /app/app.jar $PARAMS"]